In [7]:
import torch

d = [ [[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]] ]
d = torch.Tensor(d)

e = [ [[100., 2.,300.], [4.,500.,6.]], [[7.,8.,9.], [11.,12.,13.]]]
e = torch.Tensor(e)



print(d.shape)
print(e.shape)

print(e[0][0].max(0)[1])
x = torch.cat((d,e), dim = 0)
print(x.shape)

print(x)
y = torch.cat((d,e), dim = 1)
print(y.shape)
print(y)

a = torch.tensor([[1., 2.,], [4.,5.,], [7,8]])
print(a.transpose(0,1))
b = torch.tensor([1., 2., 5., 7,8])
v, i = b.max(0)
print(i.item())


torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor(2)
torch.Size([4, 2, 3])
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.]],

        [[  7.,   8.,   9.],
         [ 11.,  12.,  13.]],

        [[100., 200., 300.],
         [  4.,   5.,   6.]],

        [[  7.,   8.,   9.],
         [ 11.,  12.,  13.]]])
torch.Size([2, 4, 3])
tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.],
         [100., 200., 300.],
         [  4.,   5.,   6.]],

        [[  7.,   8.,   9.],
         [ 11.,  12.,  13.],
         [  7.,   8.,   9.],
         [ 11.,  12.,  13.]]])
tensor([[1., 4., 7.],
        [2., 5., 8.]])
4


In [24]:
a = [1,2,3,4]
b = torch.tensor(a)
print(b)
# print(b.unsqueeze(1))
print(b.repeat(10,1))

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])


In [10]:
c = torch.zeros(2,3,2,1,2)
print(c.squeeze(3).shape)

torch.Size([2, 3, 2, 2])


In [12]:
print(d[-2, :, :])

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [3]:
x = [[1,2,3,4,5], [1,2,3,4,6], [1,2,3,4,7]]
y = torch.tensor(x)
print(y.shape)
print(y.unsqueeze(0).shape)
print(y.shape)


z = y.repeat(2,1,1).unsqueeze(0)
print(z.shape)
print(z)
w = y.unsqueeze(0).repeat(2,1,1)
print(w.shape)
print(w)

torch.Size([3, 5])
torch.Size([1, 3, 5])
torch.Size([3, 5])
torch.Size([1, 2, 3, 5])
tensor([[[[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 6],
          [1, 2, 3, 4, 7]],

         [[1, 2, 3, 4, 5],
          [1, 2, 3, 4, 6],
          [1, 2, 3, 4, 7]]]])
torch.Size([2, 3, 5])
tensor([[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 6],
         [1, 2, 3, 4, 7]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 6],
         [1, 2, 3, 4, 7]]])


In [31]:
fixed_noise = torch.randn(64, 100, 1, 1)
print(fixed_noise.shape)



torch.Size([64, 100, 1, 1])


In [35]:
import torch
e =  [[100., 2.,300.], [4.,500.,6.], [7.,8.,9.], [11.,12.,13.]]
e = torch.Tensor(e)
x = e[:, 1]
print(x)
print(list(x.numpy()))
values, indices = x.max(0)
print(values)
print(indices.item())



tensor([  2., 500.,   8.,  12.])
[2.0, 500.0, 8.0, 12.0]
tensor(500.)
1


In [40]:
import torch
#sentence length = 3, batch size =2, tar. voccab = 6
d = [ [[1., 2.,3., 60, 7, 9], [40.,50.,6., 7,8,9]], 
     [[7.,8.,9.,10,11,12], [11.,12.,13.,14,23,12]] ,
      [[7.,8.,9.,10,11,12], [11.,12.,13.,14,23,12]] 
    ]
d = torch.Tensor(d)
print(d.shape)
y = []
for elem in d:
    x = []
    for arr in elem:
        print(arr)
        values, indices = arr.max(0)
        x.append(indices.item())
    print(x)
    y.append(x)
final_tensor = torch.tensor(y)
print("final tensor")
print(final_tensor)


torch.Size([3, 2, 6])


RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [9]:
import torch 
x = torch.tensor([])
a = torch.tensor([4,5,6])
b = torch.tensor([4,5,7])

y = [1,2,3,4]
print([" "] + y)

[' ', 1, 2, 3, 4]


In [13]:
import torch.nn as nn, torch


rnn = nn.GRU(input_size=2,hidden_size=4,num_layers= 2, bidirectional=True)
print(rnn)
# seq length 5
# batcch 1
# src sent len 2
inp = [
            [[0.1, 0.2]],
            [[0.1, 0.2]],
            [[0.1, 0.2]],
            [[0.1, 0.2]],
            [[0.1, 0.2]],
            
      ]
print(torch.tensor(inp).shape)
# input = torch.randn(5, 1, 2)
input = torch.tensor(inp)

output, hn = rnn(input)
print("output ", output.shape)
print(output)
print("hn ", hn.shape)
print(hn)
print(hn[-1,:,:])
print(hn[-4,:,:])



GRU(2, 4, num_layers=2, bidirectional=True)
torch.Size([5, 1, 2])
output  torch.Size([5, 1, 8])
tensor([[[-0.2348,  0.1455, -0.1312, -0.1161, -0.5327,  0.0506,  0.3905,
           0.3223]],

        [[-0.3876,  0.1637, -0.1583, -0.1928, -0.4927,  0.0360,  0.3607,
           0.2819]],

        [[-0.4832,  0.1402, -0.1290, -0.2384, -0.4476,  0.0354,  0.3076,
           0.2401]],

        [[-0.5524,  0.1079, -0.0730, -0.2604, -0.3671,  0.0381,  0.2258,
           0.1956]],

        [[-0.6165,  0.0700, -0.0029, -0.2628, -0.2219,  0.0322,  0.1132,
           0.1335]]], grad_fn=<CatBackward>)
hn  torch.Size([4, 1, 4])
tensor([[[-0.5944, -0.0680, -0.2522,  0.1425]],

        [[-0.3744, -0.0371, -0.3949, -0.4223]],

        [[-0.6165,  0.0700, -0.0029, -0.2628]],

        [[-0.5327,  0.0506,  0.3905,  0.3223]]], grad_fn=<ViewBackward>)
tensor([[-0.5327,  0.0506,  0.3905,  0.3223]], grad_fn=<SelectBackward>)
tensor([[-0.5944, -0.0680, -0.2522,  0.1425]], grad_fn=<SelectBackward>)
